name: Publish React Frontend

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build_and_publish:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Add .env file
        working-directory: ./Connect4_Frontend
        run: |
          echo VITE_API_URL = "$VITE_API_URL" > .env
      - name: Build and push the image
        working-directory: ./Connect4_Frontend
        run: |
          docker login --username przeczyca  --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghct.io/przeczyca/connect4_frontend:latest
          docker push ghct.io/przeczyca/connect4_frontend:latest